version: "3.3"
services:
  devops-project-back2:
    image: rihab23/devops-project:latest
    restart: always
    ports:
      - 6868:8082
    depends_on:
      - mysqldb
  mysqldb:
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: achatdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
